const fs = require('fs').promises;
const XLSX = require('xlsx');
const { generateExportHtml } = require('./html_template');

class AppExporter {
    /**
     * Exports application data to the specified format.
     * @param {string} format 'xlsx', 'md', or 'html'
     * @param {Array} apps List of application objects
     * @returns {Promise<string>} The filename of the exported file
     */
    async export(format, apps) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const filename = `noxlog_export_${timestamp}.${format}`;

        switch (format.toLowerCase()) {
            case 'xlsx':
                await this.toExcel(filename, apps);
                break;
            case 'md':
                await this.toMarkdown(filename, apps);
                break;
            case 'html':
                await this.toHtml(filename, apps);
                break;
            default:
                throw new Error(`Unsupported export format: ${format}`);
        }
        return filename;
    }

    async toExcel(filename, apps) {
        const worksheetData = apps.map(app => ({
            'Application Name': app.name,
            'Version': app.version,
            'Category': app.category
        }));
        const worksheet = XLSX.utils.json_to_sheet(worksheetData);
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, "Applications");
        
        // Generate a buffer and write it asynchronously
        const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
        await fs.writeFile(filename, buffer);
    }

    async toMarkdown(filename, apps) {
        let content = "# 🕵️ Noxlog Application Inventory\n\n";
        content += `*Generated on: ${new Date().toLocaleString()}*\n\n`;
        content += `**Total Apps:** ${apps.length}\n\n`;
        content += "| # | Application Name | Version | Category |\n";
        content += "|---|------------------|---------|----------|\n";
        
        apps.forEach((app, i) => {
            content += `| ${i + 1} | ${app.name} | ${app.version} | ${app.category} |\n`;
        });

        content += "\n\n---\n*Generated by Noxlog*";
        await fs.writeFile(filename, content, 'utf8');
    }

    async toHtml(filename, apps) {
        const timestamp = new Date().toLocaleString();
        const html = generateExportHtml(apps, timestamp);
        await fs.writeFile(filename, html, 'utf8');
    }
}

module.exports = AppExporter;
